### ISSUE TITLE
Activate on char-before?

### ISSUE THREAD

**Issue by artelse** [elias94/accent#1]
Just wondering why the menu is testing the character after the point. When I type and need a accent, I type the character and then invoke the menu. Perhaps make it optional?

**Comment by eliascotto** [comment]
Good idea since I had the same problem while writing. I made it optional since the effect depends on what type of cursor you have, if is bar, box, etc. If box make sense keeping it `'after`.

Just add `(setq accent-position 'before)` to your config and it will works.

**Comment by artelse** [comment]
FYI: Just read in the Emacs manual officially the point is before the cursor. So when you have a block or underline cursor the point is before the character.
https://emacsdocs.org/docs/emacs/Point
