### ISSUE TITLE
More accented letters?

### ISSUE THREAD

**Issue by linwaytin** [elias94/accent#2]
This is a simple but very useful package! Thanks a lot!
I always need to search in either Emacs or Internet for the correct symbol. I believe this package can help with this problem. 

One suggestion: Could you please add more symbols, like [caron](https://en.wikipedia.org/wiki/Caron) and [breve](https://en.wikipedia.org/wiki/Breve)? They are also common.

**Comment by eliascotto** [comment]
Thanks. Just some questions. `breve` accents is used in ancient greek and latin according to Wikipedia.
Do you usually use this kind of accents? In what language are you usually typing?

FYI I just added the standard MacOS accents, probably are the most common. But I'm open to find a way to add more if necessary.

**Comment by linwaytin** [comment]
You are right. `breve` is not common, but sometimes it appears in some people's names. 
I usually need the accents for authors' names. 

I think the package already has the most common accents. `caron` and `breve` are not common to me, either.
Maybe another idea is to change the list into some variables so that the users can easily customize them?
For example, 
```elisp
(setq letter-o (ô ö ò ó œ ø ō õ))
```
and use `letter-o` in the variable `accent-diacritics`. 
The user can then add new ones to the `letter-o`.

**Comment by eliascotto** [comment]
Okay I created a custom option to add characters.

See: https://github.com/elias94/accent#accent-custom

**Comment by linwaytin** [comment]
Thanks. That's awesome!
