### ISSUE TITLE
Add esc to dismiss the popup.

### ISSUE THREAD

**Issue by artelse** [elias94/accent#3]
Title says it all.

**Comment by eliascotto** [comment]
Not sure ESC is the way to go. Check [Emacs Key Binding Conventions](http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html).

Meanwhile you can use `C-g`

**Comment by artelse** [comment]
The last rule states ESC ESC might be used to leave a temporary state.
I didn't read a rule on the use of `C-x`. Do you know what the convention is in that case?

**Comment by eliascotto** [comment]
> The reason for this rule is that a non-prefix binding for ESC in any context prevents recognition of escape sequences as function keys in that context. 

Also `package-lint` is telling me that the key sequence is reserved. You can easily use `C-g` to close the popup.

You can include this into your config if you need.
`(define-key popup-menu-keymap (kbd "ESC") 'keyboard-quit)`
